name: knowledge-graph  # The name of the conda environment
channels:
  - conda-forge  # The conda-forge channel provides many of the packages
  - defaults  # The default channel for some other dependencies
dependencies:
  - python  # Python interpreter, no version specified to get the latest version
  - pip  # Python package installer
  - pandas  # Data manipulation library
  - numpy  # Numerical computing library
  - networkx  # Library for working with graphs and networks
  - seaborn  # Data visualisation library based on matplotlib
  - jupyterlab  # Interactive environment for working with notebooks
  - langchain  # Framework for building applications with large language models
  - pypdf  # PDF reading and manipulation
  - pyvis  # Visualisation library for graphs and networks
  - tqdm  # Progress bar library
  - yachalk  # Library for adding coloured output to the terminal
  - pip:
    - unstructured  # Handles unstructured data formats like PDFs
